Saved 45 tweets!
connection closed.
(node:33167) UnhandledPromiseRejectionWarning: Error: Querying against a released or lost connection.
    at getContext (/Users/telagraphic/Documents/front-end-tweeters/node_modules/pg-promise/lib/query.js:232:25)
    at notifyReject (/Users/telagraphic/Documents/front-end-tweeters/node_modules/pg-promise/lib/query.js:244:29)
    at Query.callback (/Users/telagraphic/Documents/front-end-tweeters/node_modules/pg-promise/lib/query.js:215:22)
    at Query.handleReadyForQuery (/Users/telagraphic/Documents/front-end-tweeters/node_modules/pg/lib/query.js:125:10)
    at Connection.<anonymous> (/Users/telagraphic/Documents/front-end-tweeters/node_modules/pg/lib/client.js:244:19)
    at Connection.emit (events.js:209:13)
    at Socket.<anonymous> (/Users/telagraphic/Documents/front-end-tweeters/node_modules/pg/lib/connection.js:126:12)
    at Socket.emit (events.js:209:13)
    at addChunk (_stream_readable.js:305:12)
    at readableAddChunk (_stream_readable.js:286:11)
(node:33167) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:33167) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:33167) UnhandledPromiseRejectionWarning: Error: Querying against a released or lost connection.
    at getContext (/Users/telagraphic/Documents/front-end-tweeters/node_modules/pg-promise/lib/query.js:232:25)
    at notifyReject (/Users/telagraphic/Documents/front-end-tweeters/node_modules/pg-promise/lib/query.js:244:29)
    at Query.callback (/Users/telagraphic/Documents/front-end-tweeters/node_modules/pg-promise/lib/query.js:215:22)
    at Query.handleReadyForQuery (/Users/telagraphic/Documents/front-end-tweeters/node_modules/pg/lib/query.js:125:10)
    at Connection.<anonymous> (/Users/telagraphic/Documents/front-end-tweeters/node_modules/pg/lib/client.js:244:19)
    at Connection.emit (events.js:209:13)
    at Socket.<anonymous> (/Users/telagraphic/Documents/front-end-tweeters/node_modules/pg/lib/connection.js:126:12)
    at Socket.emit (events.js:209:13)
    at addChunk (_stream_readable.js:305:12)
    at readableAddChunk (_stream_readable.js:286:11)
(node:33167) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:33167) UnhandledPromiseRejectionWarning: Error: Querying against a released or lost connection.
    at getContext (/Users/telagraphic/Documents/front-end-tweeters/node_modules/pg-promise/lib/query.js:232:25)
    at notifyReject (/Users/telagraphic/Documents/front-end-tweeters/node_modules/pg-promise/lib/query.js:244:29)
    at Query.callback (/Users/telagraphic/Documents/front-end-tweeters/node_modules/pg-promise/lib/query.js:215:22)
    at Query.handleReadyForQuery (/Users/telagraphic/Documents/front-end-tweeters/node_modules/pg/lib/query.js:125:10)
    at Connection.<anonymous> (/Users/telagraphic/Documents/front-end-tweeters/node_modules/pg/lib/client.js:244:19)
    at Connection.emit (events.js:209:13)
    at Socket.<anonymous> (/Users/telagraphic/Documents/front-end-tweeters/node_modules/pg/lib/connection.js:126:12)
    at Socket.emit (events.js:209:13)
    at addChunk (_stream_readable.js:305:12)
    at readableAddChunk (_stream_readable.js:286:11)
(node:33167) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:33167) UnhandledPromiseRejectionWarning: Error: Querying against a released or lost connection.
    at getContext (/Users/telagraphic/Documents/front-end-tweeters/node_modules/pg-promise/lib/query.js:232:25)
    at notifyReject (/Users/telagraphic/Documents/front-end-tweeters/node_modules/pg-promise/lib/query.js:244:29)
    at Query.callback (/Users/telagraphic/Documents/front-end-tweeters/node_modules/pg-promise/lib/query.js:215:22)
    at Query.handleReadyForQuery (/Users/telagraphic/Documents/front-end-tweeters/node_modules/pg/lib/query.js:125:10)
    at Connection.<anonymous> (/Users/telagraphic/Documents/front-end-tweeters/node_modules/pg/lib/client.js:244:19)
    at Connection.emit (events.js:209:13)
    at Socket.<anonymous> (/Users/telagraphic/Documents/front-end-tweeters/node_modules/pg/lib/connection.js:126:12)
    at Socket.emit (events.js:209:13)
    at addChunk (_stream_readable.js:305:12)
    at readableAddChunk (_stream_readable.js:286:11)
(node:33167) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:33167) UnhandledPromiseRejectionWarning: Error: Querying against a released or lost connection.
    at getContext (/Users/telagraphic/Documents/front-end-tweeters/node_modules/pg-promise/lib/query.js:232:25)
    at notifyReject (/Users/telagraphic/Documents/front-end-tweeters/node_modules/pg-promise/lib/query.js:244:29)
    at Query.callback (/Users/telagraphic/Documents/front-end-tweeters/node_modules/pg-promise/lib/query.js:215:22)
    at Query.handleReadyForQuery (/Users/telagraphic/Documents/front-end-tweeters/node_modules/pg/lib/query.js:125:10)
    at Connection.<anonymous> (/Users/telagraphic/Documents/front-end-tweeters/node_modules/pg/lib/client.js:244:19)
    at Connection.emit (events.js:209:13)
    at Socket.<anonymous> (/Users/telagraphic/Documents/front-end-tweeters/node_modules/pg/lib/connection.js:126:12)
    at Socket.emit (events.js:209:13)
    at addChunk (_stream_readable.js:305:12)
    at readableAddChunk (_stream_readable.js:286:11)
(node:33167) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
(node:33167) UnhandledPromiseRejectionWarning: Error: Querying against a released or lost connection.
    at getContext (/Users/telagraphic/Documents/front-end-tweeters/node_modules/pg-promise/lib/query.js:232:25)
    at notifyReject (/Users/telagraphic/Documents/front-end-tweeters/node_modules/pg-promise/lib/query.js:244:29)
    at Query.callback (/Users/telagraphic/Documents/front-end-tweeters/node_modules/pg-promise/lib/query.js:215:22)
    at Query.handleReadyForQuery (/Users/telagraphic/Documents/front-end-tweeters/node_modules/pg/lib/query.js:125:10)
    at Connection.<anonymous> (/Users/telagraphic/Documents/front-end-tweeters/node_modules/pg/lib/client.js:244:19)
    at Connection.emit (events.js:209:13)
    at Socket.<anonymous> (/Users/telagraphic/Documents/front-end-tweeters/node_modules/pg/lib/connection.js:126:12)
    at Socket.emit (events.js:209:13)
    at addChunk (_stream_readable.js:305:12)
    at readableAddChunk (_stream_readable.js:286:11)
